language: go

go:
  - "1.10"
  - "1.11"
  - "1.12"

services:
  - mongodb

before_script:
  - sleep 15
  - go vet ./src/rest_api/cmd/app

install:
  - export PATH=$PATH:$HOME'/go/bin'
  - export PATH=$PATH:$HOME'/go/pkg'
  - export PATH=$PATH:$HOME'/go/src'
  - export PATH=$PATH:$HOME'/JECSand/restful_api_boilerplate/bin'
  - export PATH=$PATH:$HOME'/JECSand/restful_api_boilerplate/pkg'
  - export PATH=$PATH:$HOME'/JECSand/restful_api_boilerplate/src'
  - export GOPATH=$HOME'/JECSand/restful_api_boilerplate/'
  - go get "github.com/gorilla/mux"
  - go get "github.com/gorilla/handlers"
  - go get "go.mongodb.org/mongo-driver/mongo"
  - go get "go.mongodb.org/mongo-driver/mongo/options"
  - go get "go.mongodb.org/mongo-driver/bson"
  - go get "go.mongodb.org/mongo-driver/bson/primitive"
  - go get "github.com/dgrijalva/jwt-go"
  - go get "github.com/gofrs/uuid"
  - go get "golang.org/x/crypto/bcrypt"
  - mkdir logs
  - pwd

script:
  - go test ./src/rest_api/cmd/app
